// snippet.hide
// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// snippet.show
import Foundation
import GoogleCloudTpuV2
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc

func sample(client: TpuClient, projectId: String, locationId: String, nodeId: String) async throws {
  let poller = try await client.deleteNode(
    withPolling: DeleteNodeRequest()
      .with {
        $0.name = "projects/\(projectId)/locations/\(locationId)/nodes/\(nodeId)"
      }
  )
  try await poller.wait()
  print("Success")
}
// snippet.hide

@main
struct SnippetRunner {
  static func main() async throws {
    do {
      let client = try GoogleCloudTpuV2.TpuClient()
      try await sample(
        client: client, projectId: "[placeholder]", locationId: "[placeholder]",
        nodeId: "[placeholder]")
    } catch {
      print("Error: \(error)")
    }
  }
}
