// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A accelerator type that a Node can be configured with.
public struct AcceleratorType: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The resource name.
  public var name: Swift.String

  /// The accelerator type.
  public var type: Swift.String

  /// The accelerator config.
  public var acceleratorConfigs: [AcceleratorConfig]

  /// Initialize a new instance of `AcceleratorType`.
  public init(
    name: Swift.String = Swift.String(),
    type: Swift.String = Swift.String(),
    acceleratorConfigs: [AcceleratorConfig] = [],
  ) {
    self.name = name
    self.type = type
    self.acceleratorConfigs = acceleratorConfigs
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.tpu.v2.AcceleratorType"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
