// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for [CreateNode][google.cloud.tpu.v2.Tpu.CreateNode].
///
/// [google.cloud.tpu.v2.Tpu.CreateNode]: <doc:Tpu/createNode(request:)>
public struct CreateNodeRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent resource name.
  public var parent: Swift.String

  /// The unqualified resource name.
  public var nodeId: Swift.String

  /// Required. The node.
  public var node: Node?

  /// Initialize a new instance of `CreateNodeRequest`.
  public init(
    parent: Swift.String = Swift.String(),
    nodeId: Swift.String = Swift.String(),
    node: Node? = nil,
  ) {
    self.parent = parent
    self.nodeId = nodeId
    self.node = node
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.tpu.v2.CreateNodeRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
