// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for
/// [DeleteQueuedResource][google.cloud.tpu.v2.Tpu.DeleteQueuedResource].
///
/// [google.cloud.tpu.v2.Tpu.DeleteQueuedResource]: <doc:Tpu/deleteQueuedResource(request:)>
public struct DeleteQueuedResourceRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name.
  public var name: Swift.String

  /// Optional. Idempotent request UUID.
  public var requestId: Swift.String

  /// Optional. If set to true, all running nodes belonging to this queued
  /// resource will be deleted first and then the queued resource will be
  /// deleted. Otherwise (i.e. force=false), the queued resource will only be
  /// deleted if its nodes have already been deleted or the queued resource is in
  /// the ACCEPTED, FAILED, or SUSPENDED state.
  public var force: Swift.Bool

  /// Initialize a new instance of `DeleteQueuedResourceRequest`.
  public init(
    name: Swift.String = Swift.String(),
    requestId: Swift.String = Swift.String(),
    force: Swift.Bool = Swift.Bool(),
  ) {
    self.name = name
    self.requestId = requestId
    self.force = force
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.tpu.v2.DeleteQueuedResourceRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
