// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudGax
import GoogleCloudWkt

/// Response for
/// [ListQueuedResources][google.cloud.tpu.v2.Tpu.ListQueuedResources].
///
/// [google.cloud.tpu.v2.Tpu.ListQueuedResources]: <doc:TpuClient/listQueuedResources(request:options:)>
public struct ListQueuedResourcesResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// The listed queued resources.
  public var queuedResources: [QueuedResource] = []

  /// The next page token or empty if none.
  public var nextPageToken: Swift.String = Swift.String()

  /// Locations that could not be reached.
  public var unreachable: [Swift.String] = []

  /// Initialize a new instance of `ListQueuedResourcesResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListQueuedResourcesResponse().with { $0.queuedResources = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tpu.v2.ListQueuedResourcesResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [QueuedResource] {
    return self.queuedResources
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
