// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for [ListNodes][google.cloud.tpu.v2.Tpu.ListNodes].
///
/// [google.cloud.tpu.v2.Tpu.ListNodes]: <doc:Tpu/listNodes(request:)>
public struct ListNodesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent resource name.
  public var parent: Swift.String

  /// The maximum number of items to return.
  public var pageSize: Swift.Int32

  /// The next_page_token value returned from a previous List request, if any.
  public var pageToken: Swift.String

  /// Initialize a new instance of `ListNodesRequest`.
  public init(
    parent: Swift.String = Swift.String(),
    pageSize: Swift.Int32 = Swift.Int32(),
    pageToken: Swift.String = Swift.String(),
  ) {
    self.parent = parent
    self.pageSize = pageSize
    self.pageToken = pageToken
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.tpu.v2.ListNodesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
