// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudGax
import GoogleCloudWkt

/// Response for
/// [ListRuntimeVersions][google.cloud.tpu.v2.Tpu.ListRuntimeVersions].
///
/// [google.cloud.tpu.v2.Tpu.ListRuntimeVersions]: <doc:Tpu/listRuntimeVersions(request:)>
public struct ListRuntimeVersionsResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// The listed nodes.
  public var runtimeVersions: [RuntimeVersion]

  /// The next page token or empty if none.
  public var nextPageToken: Swift.String

  /// Locations that could not be reached.
  public var unreachable: [Swift.String]

  /// Initialize a new instance of `ListRuntimeVersionsResponse`.
  public init(
    runtimeVersions: [RuntimeVersion] = [],
    nextPageToken: Swift.String = Swift.String(),
    unreachable: [Swift.String] = [],
  ) {
    self.runtimeVersions = runtimeVersions
    self.nextPageToken = nextPageToken
    self.unreachable = unreachable
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.tpu.v2.ListRuntimeVersionsResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [RuntimeVersion] {
    return self.runtimeVersions
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
