// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Network related configurations.
public struct NetworkConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the network for the TPU node. It must be a preexisting Google
  /// Compute Engine network. If none is provided, "default" will be used.
  public var network: Swift.String

  /// The name of the subnetwork for the TPU node. It must be a preexisting
  /// Google Compute Engine subnetwork. If none is provided, "default" will be
  /// used.
  public var subnetwork: Swift.String

  /// Indicates that external IP addresses would be associated with the TPU
  /// workers. If set to false, the specified subnetwork or network should have
  /// Private Google Access enabled.
  public var enableExternalIps: Swift.Bool

  /// Allows the TPU node to send and receive packets with non-matching
  /// destination or source IPs. This is required if you plan to use the TPU
  /// workers to forward routes.
  public var canIpForward: Swift.Bool

  /// Optional. Specifies networking queue count for TPU VM instance's network
  /// interface.
  public var queueCount: Swift.Int32

  /// Initialize a new instance of `NetworkConfig`.
  public init(
    network: Swift.String = Swift.String(),
    subnetwork: Swift.String = Swift.String(),
    enableExternalIps: Swift.Bool = Swift.Bool(),
    canIpForward: Swift.Bool = Swift.Bool(),
    queueCount: Swift.Int32 = Swift.Int32(),
  ) {
    self.network = network
    self.subnetwork = subnetwork
    self.enableExternalIps = enableExternalIps
    self.canIpForward = canIpForward
    self.queueCount = queueCount
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.tpu.v2.NetworkConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
