// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A network endpoint over which a TPU worker can be reached.
public struct NetworkEndpoint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The internal IP address of this network endpoint.
  public var ipAddress: Swift.String

  /// The port of this network endpoint.
  public var port: Swift.Int32

  /// The access config for the TPU worker.
  public var accessConfig: AccessConfig?

  /// Initialize a new instance of `NetworkEndpoint`.
  public init(
    ipAddress: Swift.String = Swift.String(),
    port: Swift.Int32 = Swift.Int32(),
    accessConfig: AccessConfig? = nil,
  ) {
    self.ipAddress = ipAddress
    self.port = port
    self.accessConfig = accessConfig
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.tpu.v2.NetworkEndpoint"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
