// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A TPU instance.
public struct Node: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. Immutable. The name of the TPU.
  public var name: Swift.String = Swift.String()

  /// The user-supplied description of the TPU. Maximum of 512 characters.
  public var description: Swift.String = Swift.String()

  /// Optional. The type of hardware accelerators associated with this node.
  public var acceleratorType: Swift.String = Swift.String()

  /// Output only. The current state for the TPU Node.
  public var state: Node.State = Node.State()

  /// Output only. If this field is populated, it contains a description of why
  /// the TPU Node is unhealthy.
  public var healthDescription: Swift.String = Swift.String()

  /// Required. The runtime version running in the Node.
  public var runtimeVersion: Swift.String = Swift.String()

  /// Network configurations for the TPU node. network_config and network_configs
  /// are mutually exclusive, you can only specify one of them. If both are
  /// specified, an error will be returned.
  public var networkConfig: NetworkConfig? = nil

  /// Optional. Repeated network configurations for the TPU node. This field is
  /// used to specify multiple networks configs for the TPU node. network_config
  /// and network_configs are mutually exclusive, you can only specify one of
  /// them. If both are specified, an error will be returned.
  public var networkConfigs: [NetworkConfig] = []

  /// The CIDR block that the TPU node will use when selecting an IP address.
  /// This CIDR block must be a /29 block; the Compute Engine networks API
  /// forbids a smaller block, and using a larger block would be wasteful (a
  /// node can only consume one IP address). Errors will occur if the CIDR block
  /// has already been used for a currently existing TPU node, the CIDR block
  /// conflicts with any subnetworks in the user's provided network, or the
  /// provided network is peered with another network that is using that CIDR
  /// block.
  public var cidrBlock: Swift.String = Swift.String()

  /// The Google Cloud Platform Service Account to be used by the TPU node VMs.
  /// If None is specified, the default compute service account will be used.
  public var serviceAccount: ServiceAccount? = nil

  /// Output only. The time when the node was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// The scheduling options for this node.
  public var schedulingConfig: SchedulingConfig? = nil

  /// Output only. The network endpoints where TPU workers can be accessed and
  /// sent work. It is recommended that runtime clients of the node reach out
  /// to the 0th entry in this map first.
  public var networkEndpoints: [NetworkEndpoint] = []

  /// The health status of the TPU node.
  public var health: Node.Health = Node.Health()

  /// Resource labels to represent user-provided metadata.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Custom metadata to apply to the TPU Node.
  /// Can set startup-script and shutdown-script
  public var metadata: [Swift.String: Swift.String] = [:]

  /// Tags to apply to the TPU Node. Tags are used to identify valid sources or
  /// targets for network firewalls.
  public var tags: [Swift.String] = []

  /// Output only. The unique identifier for the TPU Node.
  public var id: Swift.Int64 = Swift.Int64()

  /// The additional data disks for the Node.
  public var dataDisks: [AttachedDisk] = []

  /// Output only. The API version that created this Node.
  public var apiVersion: Node.ApiVersion = Node.ApiVersion()

  /// Output only. The Symptoms that have occurred to the TPU Node.
  public var symptoms: [Symptom] = []

  /// Shielded Instance options.
  public var shieldedInstanceConfig: ShieldedInstanceConfig? = nil

  /// The AccleratorConfig for the TPU Node.
  public var acceleratorConfig: AcceleratorConfig? = nil

  /// Output only. The qualified name of the QueuedResource that requested this
  /// Node.
  public var queuedResource: Swift.String = Swift.String()

  /// Output only. Whether the Node belongs to a Multislice group.
  public var multisliceNode: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `Node`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Node().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Represents the different states of a TPU node during its lifecycle.
  public enum State: Codable, Equatable, Sendable {
    /// TPU node state is not known/set.
    case unspecified
    /// TPU node is being created.
    case creating
    /// TPU node has been created.
    case ready
    /// TPU node is restarting.
    case restarting
    /// TPU node is undergoing reimaging.
    case reimaging
    /// TPU node is being deleted.
    case deleting
    /// TPU node is being repaired and may be unusable. Details can be
    /// found in the 'help_description' field.
    case repairing
    /// TPU node is stopped.
    case stopped
    /// TPU node is currently stopping.
    case stopping
    /// TPU node is currently starting.
    case starting
    /// TPU node has been preempted. Only applies to Preemptible TPU Nodes.
    case preempted
    /// TPU node has been terminated due to maintenance or has reached the end of
    /// its life cycle (for preemptible nodes).
    case terminated
    /// TPU node is currently hiding.
    case hiding
    /// TPU node has been hidden.
    case hidden
    /// TPU node is currently unhiding.
    case unhiding
    /// TPU node has unknown state after a failed repair.
    case unknown
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .ready: return 2
      case .restarting: return 3
      case .reimaging: return 4
      case .deleting: return 5
      case .repairing: return 6
      case .stopped: return 8
      case .stopping: return 9
      case .starting: return 10
      case .preempted: return 11
      case .terminated: return 12
      case .hiding: return 13
      case .hidden: return 14
      case .unhiding: return 15
      case .unknown: return 16
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .ready: return "READY"
      case .restarting: return "RESTARTING"
      case .reimaging: return "REIMAGING"
      case .deleting: return "DELETING"
      case .repairing: return "REPAIRING"
      case .stopped: return "STOPPED"
      case .stopping: return "STOPPING"
      case .starting: return "STARTING"
      case .preempted: return "PREEMPTED"
      case .terminated: return "TERMINATED"
      case .hiding: return "HIDING"
      case .hidden: return "HIDDEN"
      case .unhiding: return "UNHIDING"
      case .unknown: return "UNKNOWN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "READY": self = .ready
      case "RESTARTING": self = .restarting
      case "REIMAGING": self = .reimaging
      case "DELETING": self = .deleting
      case "REPAIRING": self = .repairing
      case "STOPPED": self = .stopped
      case "STOPPING": self = .stopping
      case "STARTING": self = .starting
      case "PREEMPTED": self = .preempted
      case "TERMINATED": self = .terminated
      case "HIDING": self = .hiding
      case "HIDDEN": self = .hidden
      case "UNHIDING": self = .unhiding
      case "UNKNOWN": self = .unknown
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .ready
      case 3: self = .restarting
      case 4: self = .reimaging
      case 5: self = .deleting
      case 6: self = .repairing
      case 8: self = .stopped
      case 9: self = .stopping
      case 10: self = .starting
      case 11: self = .preempted
      case 12: self = .terminated
      case 13: self = .hiding
      case 14: self = .hidden
      case 15: self = .unhiding
      case 16: self = .unknown
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .ready: return try container.encode(2)
      case .restarting: return try container.encode(3)
      case .reimaging: return try container.encode(4)
      case .deleting: return try container.encode(5)
      case .repairing: return try container.encode(6)
      case .stopped: return try container.encode(8)
      case .stopping: return try container.encode(9)
      case .starting: return try container.encode(10)
      case .preempted: return try container.encode(11)
      case .terminated: return try container.encode(12)
      case .hiding: return try container.encode(13)
      case .hidden: return try container.encode(14)
      case .unhiding: return try container.encode(15)
      case .unknown: return try container.encode(16)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Health defines the status of a TPU node as reported by
  /// Health Monitor.
  public enum Health: Codable, Equatable, Sendable {
    /// Health status is unknown: not initialized or failed to retrieve.
    case unspecified
    /// The resource is healthy.
    case healthy
    /// The resource is unresponsive.
    case timeout
    /// The in-guest ML stack is unhealthy.
    case unhealthyTensorflow
    /// The node is under maintenance/priority boost caused rescheduling and
    /// will resume running once rescheduled.
    case unhealthyMaintenance
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .healthy: return 1
      case .timeout: return 3
      case .unhealthyTensorflow: return 4
      case .unhealthyMaintenance: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "HEALTH_UNSPECIFIED"
      case .healthy: return "HEALTHY"
      case .timeout: return "TIMEOUT"
      case .unhealthyTensorflow: return "UNHEALTHY_TENSORFLOW"
      case .unhealthyMaintenance: return "UNHEALTHY_MAINTENANCE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Health/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "HEALTH_UNSPECIFIED": self = .unspecified
      case "HEALTHY": self = .healthy
      case "TIMEOUT": self = .timeout
      case "UNHEALTHY_TENSORFLOW": self = .unhealthyTensorflow
      case "UNHEALTHY_MAINTENANCE": self = .unhealthyMaintenance
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Health/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .healthy
      case 3: self = .timeout
      case 4: self = .unhealthyTensorflow
      case 5: self = .unhealthyMaintenance
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .healthy: return try container.encode(1)
      case .timeout: return try container.encode(3)
      case .unhealthyTensorflow: return try container.encode(4)
      case .unhealthyMaintenance: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// TPU API Version.
  public enum ApiVersion: Codable, Equatable, Sendable {
    /// API version is unknown.
    case unspecified
    /// TPU API V1Alpha1 version.
    case v1Alpha1
    /// TPU API V1 version.
    case v1
    /// TPU API V2Alpha1 version.
    case v2Alpha1
    /// TPU API V2 version.
    case v2
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .v1Alpha1: return 1
      case .v1: return 2
      case .v2Alpha1: return 3
      case .v2: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "API_VERSION_UNSPECIFIED"
      case .v1Alpha1: return "V1_ALPHA1"
      case .v1: return "V1"
      case .v2Alpha1: return "V2_ALPHA1"
      case .v2: return "V2"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ApiVersion/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "API_VERSION_UNSPECIFIED": self = .unspecified
      case "V1_ALPHA1": self = .v1Alpha1
      case "V1": self = .v1
      case "V2_ALPHA1": self = .v2Alpha1
      case "V2": self = .v2
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ApiVersion/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .v1Alpha1
      case 2: self = .v1
      case 3: self = .v2Alpha1
      case 4: self = .v2
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .v1Alpha1: return try container.encode(1)
      case .v1: return try container.encode(2)
      case .v2Alpha1: return try container.encode(3)
      case .v2: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tpu.v2.Node"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
