// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleType

/// A QueuedResource represents a request for resources that will be placed
/// in a queue and fulfilled when the necessary resources are available.
public struct QueuedResource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Immutable. The name of the QueuedResource.
  public var name: Swift.String = Swift.String()

  /// Output only. The time when the QueuedResource was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. The queueing policy of the QueuedRequest.
  public var queueingPolicy: QueuedResource.QueueingPolicy? = nil

  /// Output only. State of the QueuedResource request.
  public var state: QueuedResourceState? = nil

  /// Optional. Name of the reservation in which the resource should be
  /// provisioned. Format:
  /// projects/{project}/locations/{zone}/reservations/{reservation}
  public var reservationName: Swift.String = Swift.String()

  /// Resource specification.
  public var resource: OneOf_Resource? = nil

  /// Tier specifies the required tier.
  public var tier: OneOf_Tier? = nil

  /// Initialize a new instance of `QueuedResource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QueuedResource().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case createTime = "createTime"
    case tpu = "tpu"
    case spot = "spot"
    case guaranteed = "guaranteed"
    case queueingPolicy = "queueingPolicy"
    case state = "state"
    case reservationName = "reservationName"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.queueingPolicy = try container.decodeIfPresent(
      QueuedResource.QueueingPolicy.self, forKey: .queueingPolicy)
    self.state = try container.decodeIfPresent(QueuedResourceState.self, forKey: .state)
    self.reservationName = try container.decode(Swift.String.self, forKey: .reservationName)

    var resource: OneOf_Resource? = nil
    let resourceCheckAndSet = {
      if resource != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'resource'"))
      }
      resource = $0
    }
    if let tpu = try container.decodeIfPresent(QueuedResource.Tpu?.self, forKey: .tpu) {
      try resourceCheckAndSet(.tpu(tpu))
    }
    self.resource = resource

    var tier: OneOf_Tier? = nil
    let tierCheckAndSet = {
      if tier != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'tier'"
          ))
      }
      tier = $0
    }
    if let spot = try container.decodeIfPresent(QueuedResource.Spot?.self, forKey: .spot) {
      try tierCheckAndSet(.spot(spot))
    }
    if let guaranteed = try container.decodeIfPresent(
      QueuedResource.Guaranteed?.self, forKey: .guaranteed)
    {
      try tierCheckAndSet(.guaranteed(guaranteed))
    }
    self.tier = tier
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.queueingPolicy, forKey: .queueingPolicy)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.reservationName, forKey: .reservationName)

    if let choice = self.resource {
      switch choice {
      case .tpu(let value):
        try container.encode(value, forKey: .tpu)
      }
    }

    if let choice = self.tier {
      switch choice {
      case .spot(let value):
        try container.encode(value, forKey: .spot)
      case .guaranteed(let value):
        try container.encode(value, forKey: .guaranteed)
      }
    }
  }

  /// Details of the TPU resource(s) being requested.
  public struct Tpu: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. The TPU node(s) being requested.
    public var nodeSpec: [QueuedResource.Tpu.NodeSpec] = []

    /// Initialize a new instance of `Tpu`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Tpu().with { $0.nodeSpec = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Details of the TPU node(s) being requested. Users can request either a
    /// single node or multiple nodes.
    /// NodeSpec provides the specification for node(s) to be created.
    public struct NodeSpec: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Required. The parent resource name.
      public var parent: Swift.String = Swift.String()

      /// Required. The node.
      public var node: Node? = nil

      /// Either a node_id or multislice_params.
      public var nameStrategy: OneOf_NameStrategy? = nil

      /// Initialize a new instance of `NodeSpec`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = NodeSpec().with { $0.parent = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private enum CodingKeys: Swift.String, CodingKey {
        case parent = "parent"
        case nodeId = "nodeId"
        case multisliceParams = "multisliceParams"
        case node = "node"
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.parent = try container.decode(Swift.String.self, forKey: .parent)
        self.node = try container.decodeIfPresent(Node.self, forKey: .node)

        var nameStrategy: OneOf_NameStrategy? = nil
        let nameStrategyCheckAndSet = {
          if nameStrategy != nil {
            throw DecodingError.dataCorrupted(
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Multiple values set for oneof 'nameStrategy'"))
          }
          nameStrategy = $0
        }
        if let nodeId = try container.decodeIfPresent(Swift.String.self, forKey: .nodeId) {
          try nameStrategyCheckAndSet(.nodeId(nodeId))
        }
        if let multisliceParams = try container.decodeIfPresent(
          QueuedResource.Tpu.NodeSpec.MultisliceParams?.self, forKey: .multisliceParams)
        {
          try nameStrategyCheckAndSet(.multisliceParams(multisliceParams))
        }
        self.nameStrategy = nameStrategy
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.parent, forKey: .parent)
        try container.encode(self.node, forKey: .node)

        if let choice = self.nameStrategy {
          switch choice {
          case .nodeId(let value):
            try container.encode(value, forKey: .nodeId)
          case .multisliceParams(let value):
            try container.encode(value, forKey: .multisliceParams)
          }
        }
      }

      /// Parameters to specify for multislice QueuedResource requests. This
      /// message must be populated in case of multislice requests instead of
      /// node_id.
      public struct MultisliceParams: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Required. Number of nodes with this spec. The system will attempt
        /// to provision "node_count" nodes as part of the request.
        /// This needs to be > 1.
        public var nodeCount: Swift.Int32 = Swift.Int32()

        /// Optional. Prefix of node_ids in case of multislice request.
        /// Should follow the `^[A-Za-z0-9_.~+%-]+$` regex format.
        /// If node_count = 3 and node_id_prefix = "np", node ids of nodes
        /// created will be "np-0", "np-1", "np-2". If this field is not
        /// provided we use queued_resource_id as the node_id_prefix.
        public var nodeIdPrefix: Swift.String = Swift.String()

        /// Initialize a new instance of `MultisliceParams`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = MultisliceParams().with { $0.nodeCount = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.tpu.v2.QueuedResource.Tpu.NodeSpec.MultisliceParams"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      /// Either a node_id or multislice_params.
      public enum OneOf_NameStrategy: Codable, Equatable, Sendable {
        /// Optional. The unqualified resource name. Should follow the
        /// `^[A-Za-z0-9_.~+%-]+$` regex format. This is only specified when
        /// requesting a single node. In case of multislice requests,
        /// multislice_params must be populated instead.
        case nodeId(Swift.String)
        /// Optional. Fields to specify in case of multislice request.
        indirect case multisliceParams(QueuedResource.Tpu.NodeSpec.MultisliceParams?)
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.tpu.v2.QueuedResource.Tpu.NodeSpec"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.tpu.v2.QueuedResource.Tpu"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Spot tier definition.
  public struct Spot: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `Spot`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Spot().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.tpu.v2.QueuedResource.Spot"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Guaranteed tier definition.
  public struct Guaranteed: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Defines the minimum duration of the guarantee. If specified,
    /// the requested resources will only be provisioned if they can be
    /// allocated for at least the given duration.
    public var minDuration: GoogleCloudWkt.Duration? = nil

    /// Initialize a new instance of `Guaranteed`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Guaranteed().with { $0.minDuration = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.tpu.v2.QueuedResource.Guaranteed"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Defines the policy of the QueuedRequest.
  public struct QueueingPolicy: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Time flexibility specification.
    public var startTimingConstraints: OneOf_StartTimingConstraints? = nil

    /// Initialize a new instance of `QueueingPolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = QueueingPolicy().with { $0.validUntilDuration = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case validUntilDuration = "validUntilDuration"
      case validUntilTime = "validUntilTime"
      case validAfterDuration = "validAfterDuration"
      case validAfterTime = "validAfterTime"
      case validInterval = "validInterval"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var startTimingConstraints: OneOf_StartTimingConstraints? = nil
      let startTimingConstraintsCheckAndSet = {
        if startTimingConstraints != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'startTimingConstraints'"))
        }
        startTimingConstraints = $0
      }
      if let validUntilDuration = try container.decodeIfPresent(
        GoogleCloudWkt.Duration?.self, forKey: .validUntilDuration)
      {
        try startTimingConstraintsCheckAndSet(.validUntilDuration(validUntilDuration))
      }
      if let validUntilTime = try container.decodeIfPresent(
        GoogleCloudWkt.Timestamp?.self, forKey: .validUntilTime)
      {
        try startTimingConstraintsCheckAndSet(.validUntilTime(validUntilTime))
      }
      if let validAfterDuration = try container.decodeIfPresent(
        GoogleCloudWkt.Duration?.self, forKey: .validAfterDuration)
      {
        try startTimingConstraintsCheckAndSet(.validAfterDuration(validAfterDuration))
      }
      if let validAfterTime = try container.decodeIfPresent(
        GoogleCloudWkt.Timestamp?.self, forKey: .validAfterTime)
      {
        try startTimingConstraintsCheckAndSet(.validAfterTime(validAfterTime))
      }
      if let validInterval = try container.decodeIfPresent(
        GoogleType.Interval?.self, forKey: .validInterval)
      {
        try startTimingConstraintsCheckAndSet(.validInterval(validInterval))
      }
      self.startTimingConstraints = startTimingConstraints
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.startTimingConstraints {
        switch choice {
        case .validUntilDuration(let value):
          try container.encode(value, forKey: .validUntilDuration)
        case .validUntilTime(let value):
          try container.encode(value, forKey: .validUntilTime)
        case .validAfterDuration(let value):
          try container.encode(value, forKey: .validAfterDuration)
        case .validAfterTime(let value):
          try container.encode(value, forKey: .validAfterTime)
        case .validInterval(let value):
          try container.encode(value, forKey: .validInterval)
        }
      }
    }

    /// Time flexibility specification.
    public enum OneOf_StartTimingConstraints: Codable, Equatable, Sendable {
      /// Optional. A relative time after which resources should not be created.
      /// If the request cannot be fulfilled by this time the request will be
      /// failed.
      indirect case validUntilDuration(GoogleCloudWkt.Duration?)
      /// Optional. An absolute time after which resources should not be created.
      /// If the request cannot be fulfilled by this time the request will be
      /// failed.
      indirect case validUntilTime(GoogleCloudWkt.Timestamp?)
      /// Optional. A relative time after which resources may be created.
      indirect case validAfterDuration(GoogleCloudWkt.Duration?)
      /// Optional. An absolute time after which resources may be created.
      indirect case validAfterTime(GoogleCloudWkt.Timestamp?)
      /// Optional. An absolute time interval within which resources may be
      /// created.
      indirect case validInterval(GoogleType.Interval?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.tpu.v2.QueuedResource.QueueingPolicy"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Resource specification.
  public enum OneOf_Resource: Codable, Equatable, Sendable {
    /// Optional. Defines a TPU resource.
    indirect case tpu(QueuedResource.Tpu?)
  }

  /// Tier specifies the required tier.
  public enum OneOf_Tier: Codable, Equatable, Sendable {
    /// Optional. The Spot tier.
    indirect case spot(QueuedResource.Spot?)
    /// Optional. The Guaranteed tier
    indirect case guaranteed(QueuedResource.Guaranteed?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tpu.v2.QueuedResource"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
