// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleRpc

/// QueuedResourceState defines the details of the QueuedResource request.
public struct QueuedResourceState: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. State of the QueuedResource request.
  public var state: QueuedResourceState.State = QueuedResourceState.State()

  /// Output only. The initiator of the QueuedResources's current state. Used to
  /// indicate whether the SUSPENDING/SUSPENDED state was initiated by the user
  /// or the service.
  public var stateInitiator: QueuedResourceState.StateInitiator =
    QueuedResourceState.StateInitiator()

  /// Further data for the state.
  public var stateData: OneOf_StateData? = nil

  /// Initialize a new instance of `QueuedResourceState`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QueuedResourceState().with { $0.state = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case state = "state"
    case creatingData = "creatingData"
    case acceptedData = "acceptedData"
    case provisioningData = "provisioningData"
    case failedData = "failedData"
    case deletingData = "deletingData"
    case activeData = "activeData"
    case suspendingData = "suspendingData"
    case suspendedData = "suspendedData"
    case stateInitiator = "stateInitiator"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.state = try container.decode(QueuedResourceState.State.self, forKey: .state)
    self.stateInitiator = try container.decode(
      QueuedResourceState.StateInitiator.self, forKey: .stateInitiator)

    var stateData: OneOf_StateData? = nil
    let stateDataCheckAndSet = {
      if stateData != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'stateData'"))
      }
      stateData = $0
    }
    if let creatingData = try container.decodeIfPresent(
      QueuedResourceState.CreatingData?.self, forKey: .creatingData)
    {
      try stateDataCheckAndSet(.creatingData(creatingData))
    }
    if let acceptedData = try container.decodeIfPresent(
      QueuedResourceState.AcceptedData?.self, forKey: .acceptedData)
    {
      try stateDataCheckAndSet(.acceptedData(acceptedData))
    }
    if let provisioningData = try container.decodeIfPresent(
      QueuedResourceState.ProvisioningData?.self, forKey: .provisioningData)
    {
      try stateDataCheckAndSet(.provisioningData(provisioningData))
    }
    if let failedData = try container.decodeIfPresent(
      QueuedResourceState.FailedData?.self, forKey: .failedData)
    {
      try stateDataCheckAndSet(.failedData(failedData))
    }
    if let deletingData = try container.decodeIfPresent(
      QueuedResourceState.DeletingData?.self, forKey: .deletingData)
    {
      try stateDataCheckAndSet(.deletingData(deletingData))
    }
    if let activeData = try container.decodeIfPresent(
      QueuedResourceState.ActiveData?.self, forKey: .activeData)
    {
      try stateDataCheckAndSet(.activeData(activeData))
    }
    if let suspendingData = try container.decodeIfPresent(
      QueuedResourceState.SuspendingData?.self, forKey: .suspendingData)
    {
      try stateDataCheckAndSet(.suspendingData(suspendingData))
    }
    if let suspendedData = try container.decodeIfPresent(
      QueuedResourceState.SuspendedData?.self, forKey: .suspendedData)
    {
      try stateDataCheckAndSet(.suspendedData(suspendedData))
    }
    self.stateData = stateData
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.stateInitiator, forKey: .stateInitiator)

    if let choice = self.stateData {
      switch choice {
      case .creatingData(let value):
        try container.encode(value, forKey: .creatingData)
      case .acceptedData(let value):
        try container.encode(value, forKey: .acceptedData)
      case .provisioningData(let value):
        try container.encode(value, forKey: .provisioningData)
      case .failedData(let value):
        try container.encode(value, forKey: .failedData)
      case .deletingData(let value):
        try container.encode(value, forKey: .deletingData)
      case .activeData(let value):
        try container.encode(value, forKey: .activeData)
      case .suspendingData(let value):
        try container.encode(value, forKey: .suspendingData)
      case .suspendedData(let value):
        try container.encode(value, forKey: .suspendedData)
      }
    }
  }

  /// Further data for the creating state.
  public struct CreatingData: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `CreatingData`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CreatingData().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.tpu.v2.QueuedResourceState.CreatingData"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Further data for the accepted state.
  public struct AcceptedData: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `AcceptedData`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AcceptedData().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.tpu.v2.QueuedResourceState.AcceptedData"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Further data for the provisioning state.
  public struct ProvisioningData: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `ProvisioningData`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ProvisioningData().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.tpu.v2.QueuedResourceState.ProvisioningData"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Further data for the failed state.
  public struct FailedData: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The error that caused the queued resource to enter the
    /// FAILED state.
    public var error: GoogleRpc.Status? = nil

    /// Initialize a new instance of `FailedData`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FailedData().with { $0.error = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.tpu.v2.QueuedResourceState.FailedData"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Further data for the deleting state.
  public struct DeletingData: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `DeletingData`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DeletingData().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.tpu.v2.QueuedResourceState.DeletingData"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Further data for the active state.
  public struct ActiveData: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `ActiveData`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ActiveData().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.tpu.v2.QueuedResourceState.ActiveData"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Further data for the suspending state.
  public struct SuspendingData: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `SuspendingData`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SuspendingData().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.tpu.v2.QueuedResourceState.SuspendingData"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Further data for the suspended state.
  public struct SuspendedData: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `SuspendedData`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SuspendedData().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.tpu.v2.QueuedResourceState.SuspendedData"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Output only state of the request
  public enum State: Codable, Equatable, Sendable {
    case unspecified
    case creating
    case accepted
    case provisioning
    case failed
    case deleting
    case active
    case suspending
    case suspended
    case waitingForResources
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .accepted: return 2
      case .provisioning: return 3
      case .failed: return 4
      case .deleting: return 5
      case .active: return 6
      case .suspending: return 7
      case .suspended: return 8
      case .waitingForResources: return 9
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .accepted: return "ACCEPTED"
      case .provisioning: return "PROVISIONING"
      case .failed: return "FAILED"
      case .deleting: return "DELETING"
      case .active: return "ACTIVE"
      case .suspending: return "SUSPENDING"
      case .suspended: return "SUSPENDED"
      case .waitingForResources: return "WAITING_FOR_RESOURCES"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACCEPTED": self = .accepted
      case "PROVISIONING": self = .provisioning
      case "FAILED": self = .failed
      case "DELETING": self = .deleting
      case "ACTIVE": self = .active
      case "SUSPENDING": self = .suspending
      case "SUSPENDED": self = .suspended
      case "WAITING_FOR_RESOURCES": self = .waitingForResources
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .accepted
      case 3: self = .provisioning
      case 4: self = .failed
      case 5: self = .deleting
      case 6: self = .active
      case 7: self = .suspending
      case 8: self = .suspended
      case 9: self = .waitingForResources
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .accepted: return try container.encode(2)
      case .provisioning: return try container.encode(3)
      case .failed: return try container.encode(4)
      case .deleting: return try container.encode(5)
      case .active: return try container.encode(6)
      case .suspending: return try container.encode(7)
      case .suspended: return try container.encode(8)
      case .waitingForResources: return try container.encode(9)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The initiator of the QueuedResource's SUSPENDING/SUSPENDED state.
  public enum StateInitiator: Codable, Equatable, Sendable {
    case unspecified
    case user
    case service
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .user: return 1
      case .service: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "STATE_INITIATOR_UNSPECIFIED"
      case .user: return "USER"
      case .service: return "SERVICE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "STATE_INITIATOR_UNSPECIFIED": self = .unspecified
      case "USER": self = .user
      case "SERVICE": self = .service
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .user
      case 2: self = .service
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .user: return try container.encode(1)
      case .service: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Further data for the state.
  public enum OneOf_StateData: Codable, Equatable, Sendable {
    /// Output only. Further data for the creating state.
    indirect case creatingData(QueuedResourceState.CreatingData?)
    /// Output only. Further data for the accepted state.
    indirect case acceptedData(QueuedResourceState.AcceptedData?)
    /// Output only. Further data for the provisioning state.
    indirect case provisioningData(QueuedResourceState.ProvisioningData?)
    /// Output only. Further data for the failed state.
    indirect case failedData(QueuedResourceState.FailedData?)
    /// Output only. Further data for the deleting state.
    indirect case deletingData(QueuedResourceState.DeletingData?)
    /// Output only. Further data for the active state.
    indirect case activeData(QueuedResourceState.ActiveData?)
    /// Output only. Further data for the suspending state.
    indirect case suspendingData(QueuedResourceState.SuspendingData?)
    /// Output only. Further data for the suspended state.
    indirect case suspendedData(QueuedResourceState.SuspendedData?)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.tpu.v2.QueuedResourceState"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
