// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Sets the scheduling options for this node.
public struct SchedulingConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Defines whether the node is preemptible.
  public var preemptible: Swift.Bool

  /// Whether the node is created under a reservation.
  public var reserved: Swift.Bool

  /// Optional. Defines whether the node is Spot VM.
  public var spot: Swift.Bool

  /// Initialize a new instance of `SchedulingConfig`.
  public init(
    preemptible: Swift.Bool = Swift.Bool(),
    reserved: Swift.Bool = Swift.Bool(),
    spot: Swift.Bool = Swift.Bool(),
  ) {
    self.preemptible = preemptible
    self.reserved = reserved
    self.spot = spot
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.tpu.v2.SchedulingConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
