// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A service account.
public struct ServiceAccount: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Email address of the service account. If empty, default Compute service
  /// account will be used.
  public var email: Swift.String

  /// The list of scopes to be made available for this service account. If empty,
  /// access to all Cloud APIs will be allowed.
  public var scope: [Swift.String]

  /// Initialize a new instance of `ServiceAccount`.
  public init(
    email: Swift.String = Swift.String(),
    scope: [Swift.String] = [],
  ) {
    self.email = email
    self.scope = scope
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.tpu.v2.ServiceAccount"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
