// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A Symptom instance.
public struct Symptom: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Timestamp when the Symptom is created.
  public var createTime: GoogleCloudWkt.Timestamp?

  /// Type of the Symptom.
  public var symptomType: Symptom.SymptomType

  /// Detailed information of the current Symptom.
  public var details: Swift.String

  /// A string used to uniquely distinguish a worker within a TPU node.
  public var workerId: Swift.String

  /// Initialize a new instance of `Symptom`.
  public init(
    createTime: GoogleCloudWkt.Timestamp? = nil,
    symptomType: Symptom.SymptomType = Symptom.SymptomType(),
    details: Swift.String = Swift.String(),
    workerId: Swift.String = Swift.String(),
  ) {
    self.createTime = createTime
    self.symptomType = symptomType
    self.details = details
    self.workerId = workerId
  }

  /// SymptomType represents the different types of Symptoms that a TPU can be
  /// at.
  public enum SymptomType: Codable, Equatable, Sendable {
    case unspecified
    case lowMemory
    case outOfMemory
    case executeTimedOut
    case meshBuildFail
    case hbmOutOfMemory
    case projectAbuse
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .lowMemory: return 1
      case .outOfMemory: return 2
      case .executeTimedOut: return 3
      case .meshBuildFail: return 4
      case .hbmOutOfMemory: return 5
      case .projectAbuse: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "SYMPTOM_TYPE_UNSPECIFIED"
      case .lowMemory: return "LOW_MEMORY"
      case .outOfMemory: return "OUT_OF_MEMORY"
      case .executeTimedOut: return "EXECUTE_TIMED_OUT"
      case .meshBuildFail: return "MESH_BUILD_FAIL"
      case .hbmOutOfMemory: return "HBM_OUT_OF_MEMORY"
      case .projectAbuse: return "PROJECT_ABUSE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "SYMPTOM_TYPE_UNSPECIFIED": self = .unspecified
      case "LOW_MEMORY": self = .lowMemory
      case "OUT_OF_MEMORY": self = .outOfMemory
      case "EXECUTE_TIMED_OUT": self = .executeTimedOut
      case "MESH_BUILD_FAIL": self = .meshBuildFail
      case "HBM_OUT_OF_MEMORY": self = .hbmOutOfMemory
      case "PROJECT_ABUSE": self = .projectAbuse
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .lowMemory
      case 2: self = .outOfMemory
      case 3: self = .executeTimedOut
      case 4: self = .meshBuildFail
      case 5: self = .hbmOutOfMemory
      case 6: self = .projectAbuse
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .lowMemory: return try container.encode(1)
      case .outOfMemory: return try container.encode(2)
      case .executeTimedOut: return try container.encode(3)
      case .meshBuildFail: return try container.encode(4)
      case .hbmOutOfMemory: return try container.encode(5)
      case .projectAbuse: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.cloud.tpu.v2.Symptom" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
