// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol TpuStub: Sendable {
    func listNodes(
      request: ListNodesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTpuV2.ListNodesResponse

    func getNode(
      request: GetNodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTpuV2.Node

    func createNode(
      request: CreateNodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteNode(
      request: DeleteNodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func stopNode(
      request: StopNodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func startNode(
      request: StartNodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateNode(
      request: UpdateNodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listQueuedResources(
      request: ListQueuedResourcesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTpuV2.ListQueuedResourcesResponse

    func getQueuedResource(
      request: GetQueuedResourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTpuV2.QueuedResource

    func createQueuedResource(
      request: CreateQueuedResourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteQueuedResource(
      request: DeleteQueuedResourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func resetQueuedResource(
      request: ResetQueuedResourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func generateServiceIdentity(
      request: GenerateServiceIdentityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTpuV2.GenerateServiceIdentityResponse

    func listAcceleratorTypes(
      request: ListAcceleratorTypesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTpuV2.ListAcceleratorTypesResponse

    func getAcceleratorType(
      request: GetAcceleratorTypeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTpuV2.AcceleratorType

    func listRuntimeVersions(
      request: ListRuntimeVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTpuV2.ListRuntimeVersionsResponse

    func getRuntimeVersion(
      request: GetRuntimeVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTpuV2.RuntimeVersion

    func getGuestAttributes(
      request: GetGuestAttributesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTpuV2.GetGuestAttributesResponse

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
