// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for [UpdateNode][google.cloud.tpu.v2.Tpu.UpdateNode].
///
/// [google.cloud.tpu.v2.Tpu.UpdateNode]: <doc:Tpu/updateNode(request:)>
public struct UpdateNodeRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Mask of fields from [Node][Tpu.Node] to update.
  /// Supported fields: [description, tags, labels, metadata,
  /// network_config.enable_external_ips].
  public var updateMask: GoogleCloudWkt.FieldMask?

  /// Required. The node. Only fields specified in update_mask are updated.
  public var node: Node?

  /// Initialize a new instance of `UpdateNodeRequest`.
  public init(
    updateMask: GoogleCloudWkt.FieldMask? = nil,
    node: Node? = nil,
  ) {
    self.updateMask = updateMask
    self.node = node
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.tpu.v2.UpdateNodeRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
